/*
 * ======================================================================================
 * File:        gst_Frame_Saver_Plugin.h
 *
 * Purpose:     Kurento+Gstreamer plugin --- uses "Frame-Saver-Filter" for full behavior.
 *
 * History:     1. 2016-11-20   JBendor     Created --- Auto-Generated by Kurento tool
 *              2. 2016-11-24   JBendor     Adapted to "gst_frame_saver_plugin.c"
 *
 * Copyright (c) 2016 TELMATE INC. All Rights Reserved. Proprietary and confidential.
 *               Unauthorized copying of this file is strictly prohibited.
 * ======================================================================================
 */

#ifndef _GST_FRAME_SAVER_PLUGIN_H_
#define _GST_FRAME_SAVER_PLUGIN_H_

#include <config.h>


#define  NO___VIDEO_FILTER_TYPE_

#define  NO___PROVIDE_APPSINK_STUBS_

#define  NO___ALLOW_DYNAMIC_PARAMS__

#define  _SAVE_IMAGE_FRAMES_


#endif  // _GST_FRAME_SAVER_PLUGIN_H_

