/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <FrameSaverMediaPipelineImplFactory.hpp>
#include "FrameSaverMediaPipelineImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

#define GST_CAT_DEFAULT kurento_frame_saver_media_pipeline_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoFrameSaverMediaPipelineImpl"

namespace kurento
{
namespace module
{
namespace FrameSaverMediaPipeline
{

FrameSaverMediaPipelineImpl::FrameSaverMediaPipelineImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> FrameSaverMediaPipeline)  : FilterImpl (/* FIXME: Add parent class constructor params here */) 
{
  // FIXME: Implement this
}

MediaObjectImpl *
FrameSaverMediaPipelineImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> FrameSaverMediaPipeline) const
{
  return new FrameSaverMediaPipelineImpl (config, FrameSaverMediaPipeline);
}

FrameSaverMediaPipelineImpl::StaticConstructor FrameSaverMediaPipelineImpl::staticConstructor;

FrameSaverMediaPipelineImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* FrameSaverMediaPipeline */
} /* module */
} /* kurento */
