/* Autogenerated with kurento-module-creator */

#include "FrameSaverVideoFilterImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace framesaver
{

void dummyFramesaver ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<FrameSaverVideoFilter> object;

    s.SerializeNVP (object);
  }
}

} /* framesaver */
} /* module */
} /* kurento */
